### ISSUE TITLE
PHP minimal version

### ISSUE THREAD

**Issue by remicollet** [krakjoe/ilimit#6]
Can you please clarify what is minimal PHP target ?

README states 7.1+

But for now it only supports 7.3+ (at least GC_DELREF doesn't exists in 7.2)

I prefer to ask before trying to fix ;)

**Comment by krakjoe** [comment]
I think we should support back to 7.1, I hadn't yet tried a build ... you are very free to fix it :)

**Comment by krakjoe** [comment]
7614ee04523c6249a3af0da1614f8e32c2e18165 fixes the build, but the tests don't pass on 7.1 for me (1 fail) ... I've got some investigation to do ...

I haven't tested on 7.2 yet, I need CI, but it's a pain to setup and I haven't done it yet ...

**Comment by remicollet** [comment]
With 331ad8c65824588b76b0ea2f9df7205519918eee

PHP 7.1.3
`Tests passed    :   16 (100.0%) (100.0%)`

PHP 7.2.24
`Tests passed    :   16 (100.0%) (100.0%)`

**Comment by krakjoe** [comment]
Excellent, ta

**Comment by krakjoe** [comment]
I still do get a failure on 7.1 (head) ...

```
krakjoe@fiji:/opt/src/ilimit$ php -v
PHP 7.1.34dev (cli) (built: Nov 16 2019 03:26:41) ( NTS DEBUG )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
krakjoe@fiji:/opt/src/ilimit$ cat tests/009.log 

---- EXPECTED OUTPUT
OK
---- ACTUAL OUTPUT
OK
php: /opt/src/php-src/Zend/zend_gc.c:269: gc_possible_root: Assertion `(ref)->gc.u.v.type == 7 || (ref)->gc.u.v.type == 8' failed.
Aborted (core dumped)

Termsig=6
---- FAILED
```

I've no time to look deeply today, I'll look tomorrow ...
